#!/bin/bash

# Strip the extension from the name of the file
NAME=`echo "$1" | awk -F "." '{print $FNR}'`

# (TODO) Determine if we have any command line arguments
# I really don't feel like doing getopt again @_@


# Make things here
# NEW WAYYYY
#riscv-clang -cc1 $NAME.c -emit-llvm
#riscv-llc -mtriple=riscv $NAME.ll


#clang-riscv -target riscv -mriscv=RV64IM -S $NAME.c -o $NAME.S
# riscv-clang -m32 -target riscv -mriscv=RV32IM -S $NAME.c -o $NAME.S
# riscv64-unknown-elf-gcc -o $NAME.riscv $NAME.S

# # Lets dump a .o and objdump for the raw assembly
riscv64-unknown-linux-gnu-gcc -march=rv32g -mabi=ilp32d -c $NAME.c -o $NAME.o
riscv64-unknown-linux-gnu-objcopy -O binary $NAME.o $NAME.bin

# # We'll echo this for now...
riscv64-unknown-linux-gnu-objdump -d $NAME.o >> $NAME.dis

# Generate the .hex file to use in Modelsim
#srec_cat $NAME.bin -Binary -o $NAME.hex -Intel -address-length=2 -Output_Block_Size=1
